@base_url = http://localhost:3000

###
# Uploads an asset.
#

POST {{base_url}}/asset
Content-Type: image/png
File-Name: Placeholder.png

< ./test/Placeholder.png

###
# Retrieves an asset.
#

GET {{base_url}}/asset?fileName=Placeholder.png